### ISSUE TITLE
clearer help about default mode

### ISSUE THREAD

**Issue by axil** [jlevy/repren#13]
It is not clear from the documentation or from the --help page which mode is the default one.

I'd suggest either adding this into --help page:

```
- repren: Multi-pattern string replacement and file renaming
+ repren: Multi-pattern string replacement (default) and file renaming tool
```

or adding a command-line option:

```
  -p PAT_FILE, --patterns=PAT_FILE
                        file with multiple replacement patterns (see below)
+  --replace-only         do search/replace on file contents (default)
  --full                do file renames and search/replace on file contents
  --renames             do file renames only; do not modify file contents
```

or adding a simple example to the README that does nothing but a simple search-and-replace:

`repren --from center --to centre .`

This is the mode that I use most, but it was tricky to find out the exact syntax from the docs.

**Comment by jlevy** [comment]
Thanks — good point. If you'd like to file a PR the first option and any changes to the docs you think help (keeping the pydoc and readme in sync), I'd be glad to include it!

**Comment by jlevy** [comment]
Now fixed
