### ISSUE TITLE
Make available as a package in Nix

### ISSUE THREAD

**Issue by mlncn** [jlevy/repren#31]
i don't think that the maintainers of repren need to do anything but it seems weird not to mention it here; i submitted repren as a potential package available for NixOS:

[Package request: repren · Issue #361538 · NixOS/nixpkgs](https://github.com/NixOS/nixpkgs/issues/361538)

repren is amazing and i am so excited to see the Python 3 update today!

**Comment by mlncn** [comment]
… NixOS is also amazing, it's already in https://github.com/NixOS/nixpkgs/pull/361562

**Comment by jlevy** [comment]
Awesome, thanks for doing that! I've got to try nix sometime soon.
