### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by jlevy** [jlevy/repren#8]
Repren works on Mac and Linux. Currently no testing has been done on Windows. Would be great to have some help with this.

**Comment by jawshooah** [comment]
You already have a test suite set up, so why not use [Travis](https://travis-ci.org) and [Appveyor](https://appveyor.com) for continuous testing?

**Comment by jlevy** [comment]
For sure, we should add CI (and am also open to help with that). But the tests are bash-based so someone with Windows would have to help me think through how best to change or add tests for Windows. No doubt handing for backslash paths may have to be fixed up, too.

**Comment by sbrl** [comment]
Bash based stuff can be run on windows with git bash.

**Comment by jlevy** [comment]
@sbrl yes, good ideas. I don't have the time to work on Travis setup and/or Windows testing currently, but would be glad to merge in improvements if you or anyone wants to try it out, comment, and send any PRs!

**Comment by sbrl** [comment]
I'd be happy to take a look at Travis CI for you. I'll open a new issue and take a look now.
